const SUPABASE_URL='https://izvrvlufxajezukyvgue.supabase.co';
const SUPABASE_KEY='sb_publishable_5BCOeBUUn-U5c8_i3LUqmQ_MZF5eIx_';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const KEY='spend_records';
let mode='login',session=null,syncTimer=null,dirty=false,initializing=false;
const el=id=>document.getElementById(id);
function setMessage(text=''){const m=el('message');m.textContent=text;m.hidden=!text}
function setSync(text=''){el('syncStatus').textContent=text;const b=el('cloudState');if(b)b.textContent=text||'雲端同步'}
function getLocal(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveLocal(arr){localStorage.setItem(KEY,JSON.stringify(arr))}
function fingerprint(r){return [r.createdAt||'',r.name||'',r.seller||'',r.total||0,r.paid||0,r.status||'',r.shipdate||'',r.note||''].join('|')}
function mergeRecords(a,b){const out=[],seen=new Set();for(const r of [...a,...b]){const k=fingerprint(r);if(seen.has(k))continue;seen.add(k);out.push(r)}return out.sort((x,y)=>(Number(y.createdAt)||0)-(Number(x.createdAt)||0))}
async function getCloud(){const {data,error}=await db.from('spend_records').select('payload,updated_at').eq('client_id','__state__').maybeSingle();if(error)throw error;return data||null}
async function pushCloud(records){if(!session)return;setSync('同步中…');const payload={version:2,records,source:'spendbook'};const {error}=await db.from('spend_records').upsert({user_id:session.user.id,client_id:'__state__',payload},{onConflict:'user_id,client_id'});if(error)throw error;dirty=false;localStorage.setItem('spend_cloud_seen_'+session.user.id,new Date().toISOString());localStorage.setItem('spend_migrated_'+session.user.id,'1');setSync('雲端已同步')}
async function initialSync(){if(initializing||!session)return;initializing=true;try{setSync('同步中…');const local=getLocal();const cloud=await getCloud();const cloudRecords=Array.isArray(cloud?.payload?.records)?cloud.payload.records:[];const migrated=localStorage.getItem('spend_migrated_'+session.user.id)==='1';let finalRecords=[];if(!migrated&&local.length){finalRecords=mergeRecords(local,cloudRecords);saveLocal(finalRecords);await pushCloud(finalRecords)}else if(cloudRecords.length){finalRecords=cloudRecords;saveLocal(finalRecords);localStorage.setItem('spend_cloud_seen_'+session.user.id,cloud.updated_at||new Date().toISOString());setSync('雲端已同步')}else if(local.length){finalRecords=local;await pushCloud(finalRecords)}else{saveLocal([]);setSync('雲端已同步')}showApp(true)}catch(e){console.error(e);setSync('同步失敗');showApp(true)}finally{initializing=false}}
function showApp(ok){el('auth').classList.toggle('hidden',ok);el('topbar').classList.toggle('show',ok);el('appFrame').hidden=!ok;if(ok){el('accountEmail').textContent=session?.user?.email||'';try{el('appFrame').contentWindow.location.reload()}catch{}}}
function setMode(next){mode=next;el('loginTab').classList.toggle('on',mode==='login');el('signupTab').classList.toggle('on',mode==='signup');el('nameWrap').hidden=mode!=='signup';el('submitBtn').textContent=mode==='signup'?'建立帳號':'登入';setMessage('')}
async function submitAuth(){const email=el('email').value.trim(),password=el('password').value;if(!email||!password)return setMessage('請輸入 Email 和密碼。');el('submitBtn').disabled=true;setMessage('');try{if(mode==='signup'){const name=el('displayName').value.trim();const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]}}});if(error)throw error;if(data.session){session=data.session;await initialSync()}else{setMessage('註冊完成，請先到信箱點確認連結，再回來登入。');setMode('login')}}else{const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;session=data.session;await initialSync()}}catch(e){setMessage(e.message||'發生錯誤，請稍後再試。')}finally{el('submitBtn').disabled=false}}
async function resetPassword(){const email=el('email').value.trim();if(!email)return setMessage('先輸入註冊時使用的 Email。');try{const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:'https://save-radar-gold.vercel.app/reset-password'});if(error)throw error;setMessage('重設信已寄出，請到信箱查看。')}catch(e){setMessage(e.message||'無法寄出重設信。')}}
async function logout(){await db.auth.signOut();session=null;showApp(false);setMessage('已登出。')}
async function pullIfNewer(){if(!session||dirty||document.hidden)return;try{const cloud=await getCloud();if(!cloud)return;const seen=localStorage.getItem('spend_cloud_seen_'+session.user.id)||'';if(cloud.updated_at&&cloud.updated_at>seen){const recs=Array.isArray(cloud.payload?.records)?cloud.payload.records:[];saveLocal(recs);localStorage.setItem('spend_cloud_seen_'+session.user.id,cloud.updated_at);try{el('appFrame').contentWindow.location.reload()}catch{}setSync('已更新雲端資料')}}catch(e){console.error(e)}}
function schedulePush(){dirty=true;clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{try{await pushCloud(getLocal())}catch(e){console.error(e);setSync('同步失敗')}},700)}
window.addEventListener('storage',e=>{if(e.key===KEY&&session)schedulePush()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)pullIfNewer()});window.addEventListener('focus',pullIfNewer);
el('legacyFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());const arr=Array.isArray(obj)?obj:Array.isArray(obj.records)?obj.records:null;if(!arr)throw new Error();const merged=mergeRecords(getLocal(),arr);saveLocal(merged);if(session)await pushCloud(merged);setMessage(`已匯入 ${arr.length} 筆舊資料，並與現有資料合併。`);if(session){try{el('appFrame').contentWindow.location.reload()}catch{}}}catch{setMessage('這個檔案不是可用的「我的消費簿」備份。')}finally{e.target.value=''}});
(async()=>{const {data}=await db.auth.getSession();session=data.session||null;if(session)await initialSync();else showApp(false)})();
db.auth.onAuthStateChange(async(_event,newSession)=>{if(newSession&&!session){session=newSession;await initialSync()}else if(!newSession&&session){session=null;showApp(false)}});
window.setMode=setMode;window.submitAuth=submitAuth;window.resetPassword=resetPassword;window.logout=logout;